# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 8  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  s: [0.33, 0.50, 1024]   # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
# YOLOv8.0n backbone

backbone:
  # [from, repeats, module, args]
  - [-1, 1, get_orige_data, ["split"]]        #0  
  - [-1, 1, get_orige_data, ["backbone"]] 
  - [-1, 1, Conv, [64, 3, 2]]  # 2-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 3-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 5-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 7-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 9-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 11

# YOLOv8.0n head
head:
  - [[0, 6, 8, -1], 1, MSTF, [64, 6, [1,1,1], [4,4,4]]] # hidden_dim=64, start epoch                12
  - [12, 1, List_Split, [0]] #1/8                             13
  - [12, 1, List_Split, [1]] #1/16                            14
  - [12, 1, List_Split, [2]] #1/32                            15

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']] #1/32->1/16    16
  - [[-1, 14], 1, Concat, [1]]  #1/16                         17 
  - [-1, 3, C2f, [512]]  #1/16                                18 

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']] #1/16->1/8       19
  - [[-1, 13], 1, Concat, [1]]  # 1/8                           20
  - [-1, 3, C2f, [256]]  #1/8                                   21

  - [-1, 1, Conv, [256, 3, 2]]  #1/8->1/16                      22
  - [[-1, 18], 1, Concat, [1]]  #1/16                           23
  - [-1, 3, C2f, [512]]  #1/16                                  24

  - [-1, 1, Conv, [512, 3, 2]]  #1/16->1/32                       25
  - [[-1, 15], 1, Concat, [1]]  #1/32
  - [-1, 3, C2f, [1024]]  #1/32                                  27

  - [[21, 24, 27], 1, Detect, [nc]]  # Detect(P3, P4, P5) 20