#!/usr/bin/env python3
"""Create the small YAML bridge required by the historical YOLOFT loader.

The canonical XS-VID v2 JSON and generated YOLO labels remain the source data.
It derives labels through the dataset conversion utility and writes portable
split lists and a YAML bridge. Canonical annotations are never changed.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path


NAMES = (
    "bicycle-static",
    "bicycle-person",
    "car",
    "person",
    "ignore",
    "truck",
    "boat",
)


def write_legacy_split(root: Path, split_name: str) -> Path:
    """Write image-root-relative paths expected by the historical loader."""
    source = root / "splits" / f"{split_name}.txt"
    destination = root / "splits" / f"legacy_{split_name}.txt"
    image_root = (root / "images").resolve()
    lines = []

    for raw_line in source.read_text(encoding="utf-8").splitlines():
        raw_line = raw_line.strip()
        if not raw_line:
            continue
        image_path = Path(raw_line)
        if not image_path.is_absolute():
            image_path = source.parent / image_path
        image_path = image_path.resolve()
        try:
            relative_path = image_path.relative_to(image_root)
        except ValueError as exc:
            raise ValueError(f"{source}: image is outside {image_root}: {raw_line}") from exc
        lines.append(f"./{relative_path.as_posix()}")

    if not lines:
        raise ValueError(f"{source}: split is empty")
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return destination


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-root", type=Path, required=True, help="Downloaded XS-VID v2 root")
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--regenerate-labels", action="store_true", help="Repair partial/stale label preparation")
    parser.add_argument(
        "--detection-protocol",
        choices=("canonical", "paper"),
        default="paper",
        help="Use paper for reported-result reproduction; canonical for new benchmark results.",
    )
    args = parser.parse_args()

    root = args.data_root.resolve()
    required = (
        root / "images",
        root / "splits" / "train.txt",
        root / "splits" / "val_dev.txt",
        root / "splits" / "test.txt",
        root / "annotations" / "train.json",
        root / "annotations" / "val_dev.json",
        root / "annotations" / "test.json",
    )
    missing = [str(path) for path in required if not path.exists()]
    if missing:
        raise FileNotFoundError("Missing release files:\n" + "\n".join(missing))

    # The compact release keeps canonical JSON rather than pre-materializing
    # one label file per frame. Generate the legacy labels only when needed.
    if args.regenerate_labels or not (root / "labels").is_dir():
        converter = root / "tools" / "prepare_yolo_labels.py"
        if not converter.is_file():
            raise FileNotFoundError(f"Missing label conversion utility: {converter}")
        subprocess.run(
            [sys.executable, str(converter), "--root", str(root)],
            check=True,
        )

    if args.detection_protocol == "paper":
        evaluation_json = root / "annotations" / "protocols" / "paper_detection_test.json"
    else:
        evaluation_json = root / "annotations" / "test.json"
    if not evaluation_json.is_file():
        raise FileNotFoundError(evaluation_json)

    for split_name in ("train", "val_dev", "test"):
        write_legacy_split(root, split_name)

    output = args.output or root / "legacy_yoloft.yaml"
    output.parent.mkdir(parents=True, exist_ok=True)
    yaml_root = Path(os.path.relpath(root, output.parent)).as_posix()
    yaml_evaluation = Path(os.path.relpath(evaluation_json, output.parent)).as_posix()
    names = "".join(f"  {index}: {name}\n" for index, name in enumerate(NAMES))
    output.write_text(
        "# Generated by YOLOFT tools/xsvid/prepare_legacy_layout.py\n"
        "yaml_relative_root: true\n"
        f"path: {yaml_root}\n"
        "train: splits/legacy_train.txt\n"
        "val: splits/legacy_val_dev.txt\n"
        "test: splits/legacy_test.txt\n\n"
        "labels_dir: labels\n"
        "images_dir: images\n"
        "StreamVideoSampler: True\n"
        "train_video_length: [1]\n"
        "train_video_interval: 2\n\n"
        f"eval_ann_json: {yaml_evaluation}\n"
        "classes_map: [0, 1, 2, 3, 4, 5, 6]\n"
        "names:\n" + names,
        encoding="utf-8",
    )
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
