# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 8  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  l: [1.00, 1.00, 512]  # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
# YOLOv8.0n backbone

backbone:
  # [from, repeats, module, args]
  - [-1, 1, get_orige_data, ["split"]]        #0  
  - [-1, 1, get_orige_data, ["backbone"]] 
  - [-1, 1, Conv, [64, 3, 2]]  # 2-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 3-P2/4
  - [-1, 2, C2f_DCNV3, [128, True]] #4
  - [-1, 1, Conv, [256, 3, 2]]  # 5-P3/8
  - [-1, 4, C2f_DCNV3, [256, True]] #6
  - [-1, 1, Conv, [512, 3, 2]]  # 7-P4/16
  - [-1, 4, C2f_DCNV3, [512, True]] #8
  # - [-1, 1, Conv, [1024, 3, 2]]  # 9-P5/32
  # - [-1, 3, C2f_DCNV3, [1024, True]]
  - [-1, 1, SPPF, [512, 5]]  # 9

# YOLOv8.0n head
head:
  - [[0, 4, 6, -1], 1, MSTF_STREAM2, [4, 1.0, 1.0]] # start epoch, depth, width  10

  - [10, 1, List_Split, [0]] #1/8                             11
  - [10, 1, List_Split, [1]] #1/16                            12
  - [10, 1, List_Split, [2]] #1/32                            13

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']] #1/32->1/16    18
  - [[-1, 12], 1, Concat, [1]]  #1/16                         19 
  - [-1, 3, C2f, [256]]  #1/16                                20 

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']] #1/16->1/8       21
  - [[-1, 11], 1, Concat, [1]]  # 1/8                           22
  - [-1, 3, C2f, [128]]  #1/8                                   23

  - [-1, 1, Conv, [128, 3, 2]]  #1/8->1/16                      24
  - [[-1, 16], 1, Concat, [1]]  #1/16                           25
  - [-1, 3, C2f, [256]]  #1/16                                  26

  - [-1, 1, Conv, [256, 3, 2]]  #1/16->1/32                       27
  - [[-1, 13], 1, Concat, [1]]  #1/32
  - [-1, 3, C2f, [512]]  #1/32                                  29

  - [[19, 22, 25], 1, Detect, [nc]]  # Detect(P3, P4, P5) 20